# Generated by Django 3.0.5 on 2020-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.CharField(max_length=15)),
                ('upassword', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
